### ISSUE TITLE
[iOS] Login crashes when Deployment Target is 12.1

### ISSUE THREAD

**Issue by someshubham** [Web3Auth/web3auth-flutter-sdk#14]
**Problem**:
The documentation mentions that iOS 12+ is supported, but the Login function crashes when the App Deployment target is 12.1. When selecting any Provider for login, the Pop-up opens and crashes.

<img width="937" alt="Screenshot 2022-07-15 at 6 10 55 PM" src="https://user-images.githubusercontent.com/49554541/179224936-4732394c-1d04-4f98-9d2e-7fc2f4416881.png">

[Documentation for iOS](https://github.com/Web3Auth/web3auth-swift-sdk)

**Error Snippet Received**:
`[AXRuntimeCommon] AX Lookup problem - errorCode:1100 error:Permission denied portName:'com.apple.iphone.axserver' PID:452`

**Solution Found**:
Updating the Deployment Target to iOS 13 fixes the issue

**Additional Queries**:
Can we update the SDK to work with iOS 12.1? If not, maybe we could update the documentation to mention the supported versions.

**Comment by chaitanyapotti** [comment]
we updated the docs to reflect that
