### ISSUE TITLE
Error when using custom auth (firebase)

### ISSUE THREAD

**Issue by nisa10880** [Web3Auth/web3auth-flutter-sdk#23]
I have an error when I trie to login with firebase and web3auth. I followed the guide to use firebase and web3auth together.

This is my code

`    HashMap<String, LoginConfigItem>? loginConfig = HashMap<String, LoginConfigItem>();

    loginConfig['jwt'] = LoginConfigItem(
      verifier: "",
      typeOfLogin: TypeOfLogin.jwt,
      name: "test",
      clientId: 'my-firebase-client-id',
    );

    await Web3AuthFlutter.init(Web3AuthOptions(
        redirectUrl: redirectUrl,
        clientId:
            'my-web3authapp-client-id',
        network:Network.testnet,
        loginConfig: loginConfig
        // loginConfig: loginConfig,
        ));`

And I got this error ans it's not very helpful, I cannot find what parameter is wrong.

**PlatformException (PlatformException(INVALID_ARGUMENTS, Invalid Flutter iOS plugin init params, null, null))**

I am running the app in a IOS simulator with flutter 3.3.5

**Comment by nisa10880** [comment]
I case you faced the same issue. I solved by using this branch https://github.com/Web3Auth/web3auth-flutter-sdk/tree/jwt-login-fixes . 

Now I have blank screen after the web3auth web view appear.
I am trying to use Firebase phone auth, do you think it's possible. I have a doubt about which custom provider clientId should I enter.

**Comment by flodaniel** [comment]
@nisa10880 i figured it out. Based on your code snipped above the thing i would change is to always use the clientID you got  from web3auth, also in the LoginConfigItem. The final login call then looks like this: 
```
        // first login with firebase, then with web3auth
        final firebaseResponse = await signInWithGoogle();
        final idToken =
            (await firebaseResponse.user?.getIdToken(true)).toString();
        // Login
        final web3Login = await Web3AuthFlutter.login(
          LoginParams(
            loginProvider: Provider.jwt,
            extraLoginOptions: ExtraLoginOptions(
              id_token: idToken,
              domain: 'firebase',
            ),
          ),
        );
```

**Comment by shahbaz17** [comment]
Hey @flodaniel @nisa10880 

Could you try again with the latest SDK? 

We also have an example app https://github.com/Web3Auth/examples/tree/main/flutter/flutter-firebase-example.

And let us know if you can reproduce the same or not.

**Comment by flodaniel** [comment]
Hey @shahbaz17,
as per my last comment I got this already working back in november :)
