### ISSUE TITLE
Why is it designed in the way that the private key is returned in response?

### ISSUE THREAD

**Issue by kabaluyot** [Web3Auth/web3auth-flutter-sdk#41]
I am following this documentation: https://web3auth.io/docs/connect-blockchain/ethereum/flutter 

Isn't it a bit problematic that dApps can access private keys of the signed-in users? Like any dApp can literally store users private keys

**Comment by chaitanyapotti** [comment]
All keys are app-scoped. You can read more about it here: https://web3auth.io/docs/how-web3auth-works

**Comment by kabaluyot** [comment]
@chaitanyapotti Even if app-scoped, does it mean users need to trust the dApp implementor? That when they sign in they don't f*** the private keys and whatever assets behind that private key? (esp if Torus interoperability is enabled?)

**Comment by chaitanyapotti** [comment]
Yes. the dapp acts as a wallet. If torus interoperability is enabled, it means that dapp's private key shows up in the torus wallet not the other way around

**Comment by kabaluyot** [comment]
But what makes it different vs the dApp/platform generate key-pair for users themself and add social logins if the trust would be on the implementor side?

Because I can create a platform, use Web3Auth for social login, then secretly have an "extra endpoint" upload to API the generated private key of these users. If the answer would be to open-source the dApp which most wallets do -- not likely be the option

Please enlighten me :D
