### ISSUE TITLE
Few questions on the custom JWT auth

### ISSUE THREAD

**Issue by lukaskai** [Web3Auth/web3auth-flutter-sdk#42]
Hey Guys! 

Let's say we go with Flutter SDK and custom JWT auth and mandatory 2FA. So on the sign up, the wallet creation would happen in the background using our JWT.

How is the 2FA being setup? Will user be required to set it up using your UI (will there be a pop-up there), or we should use somehow the dappshare?

**Comment by chaitanyapotti** [comment]
Using this sdk, the user sets up MFA in our UI.
For UI less SDK, pls use core kit
