### ISSUE TITLE
Web3Auth login flow failed

### ISSUE THREAD

**Issue by peerwaya** [Web3Auth/web3auth-flutter-sdk#57]
Login fails on iOS using firebase custom auth on version web3auth_flutter 3.0.1. Works on Android

**Comment by chaitanyapotti** [comment]
we just released 3.1.0 with a bunch of fixes.
pls test and let us know

**Comment by shahbaz17** [comment]
Hey @peerwaya 

Please follow [this working firebase example ](https://github.com/Web3Auth/web3auth-pnp-examples/tree/main/flutter/flutter-firebase-example) as per the latest SDK.

**Comment by peerwaya** [comment]
Tried 3.1.0, it still does not work. Returns the error ```Web3Auth login flow failed```

**Comment by peerwaya** [comment]
The issue is only happening on IOS. Android works fine.

**Comment by peerwaya** [comment]
I think this is specific to iOS and firebase verifier using JWT. I tried the example app and it worked well. Switching back to 2.0.1, everything works well.  I also tried logging the error on the swift side and was getting `unknown error`

**Comment by peerwaya** [comment]
I have fixed the issue here https://github.com/Web3Auth/web3auth-swift-sdk/pull/47
