### ISSUE TITLE
dependencies incompatibility 

### ISSUE THREAD

**Issue by arturch2011** [Web3Auth/web3auth-flutter-sdk#67]
Hi,
when I try to build my app with web3auth_flutter: ^3.1.6 and flutter_stripe: ^10.0.0 the build fails and return this errors:

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class org.bouncycastle.LICENSE found in modules bcprov-jdk15on-1.68.jar -> jetified-bcprov-jdk15on-1.68 (org.bouncycastle:bcprov-jdk15on:1.68) and bcprov-jdk15to18-1.69.jar -> jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'org/bouncycastle/x509/CertPathReviewerMessages_de.properties' from inputs:
      - /home/hashimoto/.gradle/caches/transforms-4/3d7198f171a217e2e3b7929456a5987c/transformed/jetified-bcprov-jdk15to18-1.69.jar
      - /home/hashimoto/.gradle/caches/transforms-4/038d0987e194dd385819943f7b265100/transformed/jetified-bcprov-jdk15on-1.68.jar
     Adding a packagingOptions block may help, please refer to
     https://developer.android.com/reference/tools/gradle-api/7.3/com/android/build/api/dsl/ResourcesPackagingOptions
     for more information

I alredy tried diferent versions of each package but the problem persist, can anyone help me ?

**Comment by AyushBherwani1998** [comment]
@arturch2011 this issue happens because there are two different versions of transitive dependencies. You can ignore one of the module in the app-level gradle.  

```
configurations {
    all {
        exclude(group = "org.bouncycastle", module = "bcprov-jdk15on-1.68")
    }
}
```
