### ISSUE TITLE
Why are your docs misleading?

### ISSUE THREAD

**Issue by Daeon97** [Web3Auth/web3auth-flutter-sdk#73]
I am trying to integrate web3Auth into my Flutter app. However the steps regarding setting up your package to work on iOS at https://pub.dev/packages/web3auth_flutter is different from the content on your site at https://web3auth.io/docs/sdk/pnp/flutter/install. I am literally and figuratively confused

**Steps to reproduce**

1. Go to https://pub.dev/packages/web3auth_flutter

2. Check the requirements for iOS under the **Requirements** section. It currently says this
<img width="787" alt="Screenshot 2024-05-13 at 5 25 04 PM" src="https://github.com/Web3Auth/web3auth-flutter-sdk/assets/40745212/ed0acdb3-e736-45d5-b3f1-65f470746a26">

> For iOS, only iOS 12+

but then you go ahead to say 

> For iOS build: platform :ios needs to be 14.0

This is a contradictory statement

3. Scroll down to the iOS subsection under the **Configuration** section. It currently says this. I honestly have no idea what this is supposed to mean
<img width="316" alt="Screenshot 2024-05-13 at 5 28 58 PM" src="https://github.com/Web3Auth/web3auth-flutter-sdk/assets/40745212/a8c25bee-c5a2-43c1-942c-80dbf167c009">

Yeah. Just that. Nothing else

4. Now go to the docs on your website https://web3auth.io/docs/sdk/pnp/flutter/install

5. Scroll down to where it mentions configuring Web3Auth for iOS, specifically the **Add dependencies** section it currently says this
<img width="999" alt="Screenshot 2024-05-13 at 5 36 51 PM" src="https://github.com/Web3Auth/web3auth-flutter-sdk/assets/40745212/ee714d4c-3e2a-432c-9c8b-1ec5986fdd14">

I am just really confused. Which should I follow? https://pub.dev/packages/web3auth_flutter? https://web3auth.io/docs/sdk/pnp/flutter/install? Or am I supposed to somehow combine both?

**Comment by chaitanyapotti** [comment]
We fixed the readme now
