### ISSUE TITLE
How do I specify correct `android:scheme` on Android

### ISSUE THREAD

**Issue by Daeon97** [Web3Auth/web3auth-flutter-sdk#81]
In your [example app](https://github.com/Web3Auth/web3auth-flutter-sdk/blob/master/example/android/app/src/main/AndroidManifest.xml) `AndroidManifest.xml` file, you have this

<img width="823" alt="Screenshot 2024-07-12 at 8 50 18 AM" src="https://github.com/user-attachments/assets/3eda3c26-0f7d-411b-bded-0d2c5142ba65">

However you never specify where to get or how to know the correct `android:scheme` to specify here. This is neither in your docs nor explained in the example app itself

In your docs, you use this to illustrate
<img width="973" alt="Screenshot 2024-07-12 at 9 03 31 AM" src="https://github.com/user-attachments/assets/58d060f2-7b1e-4445-a6b2-d86e52c5ca74">

`Accept URIs: w3a://com.example.w3aflutter` by deduction I guess `w3a://` is the `android:scheme` here however my guess may be wrong because this is not clearly stated in the docs and nothing is said about how to get correct `android:scheme` or the implications of not using the correct `android:scheme`. Now, in your example app you use `android:scheme="torusapp"`

I am really confused. With relation to this library, should `android:scheme` conform to a specific pattern or value or not and also could you guys update your docs to reflect how exactly one can get, set and/or correctly specify this `android:scheme`

**Comment by AyushBherwani1998** [comment]
Hey @Daeon97 they scheme would be `w3a` instead of `w3a://`. The application will create the url based on the scheme, host and path.

**Comment by Daeon97** [comment]
> Hey @Daeon97 they scheme would be `w3a` instead of `w3a://`. The application will create the url based on the scheme, host and path.

Alright thanks @AyushBherwani1998
