### ISSUE TITLE
apple login invalid_client

### ISSUE THREAD

**Issue by thanhvu260696** [Web3Auth/web3auth-flutter-sdk#84]
I'm getting an invalid_client error when trying to authenticate my app with the web3authFutter. It doesn't run on a real machine but the simulator still works. Here are some details about the issue I'm running into:

FutureOr initPlatform(InitPlatform event, Emitter emit) async {
    Uri redirectUrl;
   
    if (Platform.isAndroid) {
      redirectUrl = Uri.parse('w3a://com.hyratek.wallet/auth');
    } else if (Platform.isIOS) {
      redirectUrl = Uri.parse('com.hyratek.wallet://auth');
    } else {
      return;
      // throw UnKnownException('Unknown platform');
    }
    await Web3AuthFlutter.init(Web3AuthOptions(
      clientId: clientId,
      network: Network.sapphire_devnet,
      redirectUrl: redirectUrl,
      // 259200 allows user to stay authenticated for 3 days with Web3zAuth.
      // Default is 86400, which is 1 day.
      // sessionTime: 259200,
    ));

    await Web3AuthFlutter.initialize();
}

 Future<Web3AuthResponse> withApple() async {
    try {
      return await Web3AuthFlutter.login(
        LoginParams(
          loginProvider: Provider.apple,
        ),
      );
    } catch (e) {
      return Future.error('withApple error occurred: $e');
    }
  }

Error log : 
[{"errorMsg":"invalid_client","errorStack":"@https://auth.web3auth.io/v8/assets/index-BYv4LlQ9.js:2:2707\npt@https://auth.web3auth.io/v8/assets/index-BYv4LlQ9.js:2:2711\n@https://auth.web3auth.io/v8/assets/index-BYv4LlQ9.js:2:11293","title":"Mount Error","createdAt":"30/09/2024, 16:33:05","info":{"customAuthState":{"client":"BAzopCaemV9gsgv3ZN3c77NZlA9Y55B1PStlBfiTAeaSqdjKgtn-0AhyMbH57JIOKnMRZ_PCrSjQ82Zw3YmSiH0","currentLoginProvider":"apple","popupWindow":"false","whiteLabel":"{\"mode\":\"light\"}","keyMode":"v1","loginId":"07cfe4c865ae1187b49e8c4ad84ea92d28e9d34330003e1f0387f8b9f1a4285d","sessionNamespace":"","socialFactorFlow":"","version":"8","instanceId":"4uc3swijmsf","verifier":"web3auth","typeOfLogin":"apple","redirectToOpener":false},"customAuthArgs":{"aggregateVerifierType":"single_id_verifier","verifierIdentifier":"web3auth-auth0-apple-sapphire-devnet","subVerifierDetailsArray":[{"typeOfLogin":"apple","verifier":"web3auth","clientId":"ADG0f0EZsBHvcbu2in7W938XngxJQJrJ","jwtParams":{"domain":"https://torus-test.auth0.com","connection":"apple"},"customState":{"client":"BAzopCaemV9gsgv3ZN3c77NZlA9Y55B1PStlBfiTAeaSqdjKgtn-0AhyMbH57JIOKnMRZ_PCrSjQ82Zw3YmSiH0","currentLoginProvider":"apple","popupWindow":"false","whiteLabel":"{\"mode\":\"light\"}","keyMode":"v1","loginId":"07cfe4c865ae1187b49e8c4ad84ea92d28e9d34330003e1f0387f8b9f1a4285d","sessionNamespace":"","socialFactorFlow":"","version":"8"}}]},"customAuthError":"invalid_client","customAuthHashParams":{"error":"invalid_request","error_description":"invalid_client","state":"eyJjbGllbnQiOiJCQXpvcENhZW1WOWdzZ3YzWk4zYzc3TlpsQTlZNTVCMVBTdGxCZmlUQWVhU3FkaktndG4tMEFoeU1iSDU3SklPS25NUlpfUENyU2pRODJadzNZbVNpSDAiLCJjdXJyZW50TG9naW5Qcm92aWRlciI6ImFwcGxlIiwicG9wdXBXaW5kb3ciOiJmYWxzZSIsIndoaXRlTGFiZWwiOiJ7XCJtb2RlXCI6XCJsaWdodFwifSIsImtleU1vZGUiOiJ2MSIsImxvZ2luSWQiOiIwN2NmZTRjODY1YWUxMTg3YjQ5ZThjNGFkODRlYTkyZDI4ZTlkMzQzMzAwMDNlMWYwMzg3ZjhiOWYxYTQyODVkIiwic2Vzc2lvbk5hbWVzcGFjZSI6IiIsInNvY2lhbEZhY3RvckZsb3ciOiIiLCJ2ZXJzaW9uIjoiOCIsImluc3RhbmNlSWQiOiI0dWMzc3dpam1zZiIsInZlcmlmaWVyIjoid2ViM2F1dGgiLCJ0eXBlT2ZMb2dpbiI6ImFwcGxlIiwicmVkaXJlY3RUb09wZW5lciI6ZmFsc2V9"}}}]

Video: 
https://github.com/user-attachments/assets/775c2db1-968e-4a7a-b42e-6fe4c73d46d9

I really need your help
Thanks a lot!

**Comment by grvgoel81** [comment]
@thanhvu260696 Hi, pls open issue on https://community.web3auth.io/. Thanks!
