### ISSUE TITLE
Web3Auth Flutter throws PlatformException on initialization 

### ISSUE THREAD

**Issue by mayananand369** [Web3Auth/web3auth-flutter-sdk#87]
`Web3AuthFlutter.initialize()` is throwing a PlatformException upon starting my app on Android emulator specifically. Due to this, the app gets stuck on the splash screen.
I attaching the screen recording of the issue for reference:

https://github.com/user-attachments/assets/6c470d6a-6988-44f1-8f8c-c44e349319fc

**Comment by AyushBherwani1998** [comment]
Hey this issue was fixed, it was because of config API failing during the initialization. No version was required, it was a hot fix.
